[settings]
experimental = true
env_shell_expand = true

[tools]
packer = "1.8.7"
ruby = "3.2.10"
vault = "1.14.4"
terraform = "1.0.0"
python = "3.14.3"
pipx = "1.4.3"
rust = "latest"
bun = "latest"
mysql = "8.0.34"
uv = "latest"
terraform-ls = "0.36.4"
erlang = "latest"
spacectl = "1.16.0"
golangci-lint = "latest"

[tools.node]
version = "lts"
postinstall = '''
echo "=== NodeJS: Installing Claude Code Router"
npm install -g @musistudio/claude-code-router
'''

[tools.go]
version = "latest"
postinstall = '''
echo "=== Go (package): Installing gopls"
go install golang.org/x/tools/gopls@latest

echo "=== Go (local): Installing scrpt"
cd ~/Buckle/scrpt; go install .
''''

