[settings]
env_shell_expand = true

[tools]
packer = "1.8.7"
ruby = "3.2.8"
vault = "1.14.4"
terraform = "1.0.0"
# go = "1.25.7"
node = "lts"
python = "3.13.5t"
pipx = "1.4.3"
rust = "latest"
bun = "latest"
mysql = "8.0.34"
uv = "latest"
terraform-ls = "0.36.4"
erlang = "28.0.1"
spacectl = "1.16.0"
golangci-lint = "latest"

[tools.go]
version = "1.25.7"
postinstall = "go install golang.org/x/tools/gopls@latest"

